# 1. Stack two arrays vertically

Use the array given below:

array1 = np.arange(10).reshape(2,-1)

array2 = np.repeat(1, 10).reshape(2,-1)

In [2]:
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)

NameError: name 'np' is not defined

In [3]:
import numpy as np
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)

array3 = np.concatenate([array1,array2])

In [4]:
import numpy as np
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)

array3 = np.concatenate([array1,array2])
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
